version: "3.9"

services:
  ocr-service:
    build:
      context: tesseract-ocr
      dockerfile: Dockerfile
    container_name: ocr-service
    ports:
      - "8081:8080"
    restart: unless-stopped

  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8082:8080"
    restart: unless-stopped