version: "3.9"

services:
  ocrservice:
    build:
      context: tesseract-ocr
      dockerfile: Dockerfile
    container_name: ocrservice
    ports:
      - "8081:8080"
    restart: unless-stopped

  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8082:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app/app